script: bash ./deploy-gh-pages.sh
env:
  global:
  - GH_REF: github.com/mooniak/ayanna-narrow.git
  - secure: PTsOD7eC4VGuh6OHwp+NnvQGIYULPjw//D5SQEbJOlEF9nM8JWD2hHcT3bZ5XSIA82wG5JGXgWPI2PyS14Klcaiv3Z9k4+jHWBDN3/2FgDRbv+S/pAyp3iePZsvyIPE2rVY9AD7CHoNvMfSxLO77djjIEcj04oaYKj82w65Hlao=
